from django.conf import settings

PAYSTACK_SUCCESS_STATUS = "success" 

BREVO_SENDER = {
    "email": settings.BREVO_SENDER_EMAIL,
    "name": settings.BREVO_SENDER_NAME
}


SUBSCRIPTION_SUBSCRIBED = "SUBSCRIBED"
SUBSCRIPTION_CANCELLED = "CANCELLED"
SUBSCRIPTION_EXPIRED = "EXPIRED"
SUBSCRIPTION_APPROVED = "EXPIRING_SOON"
