
from django.urls import path
from .views import(
    AllFoodView, 
    AddToCartView,
    RemoveFromCartView,
    CancelOrderView,
    UpdateOrderDetailView, 
    CheckOutView, 
    AllOrdersView, 
    OrderStatusUpdateView,
    OrderDetailView,
    InitializePaymentView,
    VerifyPaymentView,
    PayStackWebhookView,
    CreateReviewView,
    UpdateReviewView,
    OrderReviewDetailView,
    FoodReviewsView,
    FoodDetailView,
    VendorListView,
    VendorDetailView,
    VendorFoodListView,
    VendorReviewsView,
    VendorRegistrationView,
    VendorDashboardView,
    VendorDashboardStatsView,
    VendorProfileUpdateView,
    VendorFoodCreateView,
    VendorFoodsView,
    VendorFoodDetailView,
    VendorFoodToggleAvailabilityView,
    VendorOrderListView,
    VendorOrderDetailView,
    AdminVendorListView,
    AdminVendorDetailView,
    AdminApproveVendorView,
    AdminVendorRejectView,
    AdminVendorActivateView,
    AdminVendorDeactivateView,
    CategoryListView,
    CategoryFoodsView,
    AdminCategoryCreateView,
    AdminCategoryDetailView

)

app_name = "food"
urlpatterns = [
    path("menu/", AllFoodView.as_view(), name="menu"),
    path("my-orders/", AllOrdersView.as_view(), name="my-orders"),
    path("add_to_cart/", AddToCartView.as_view(), name="add"),
    path("remove/", RemoveFromCartView.as_view(), name="remove"),
    path("order/cancel/", CancelOrderView.as_view(), name="cancel"),
    path("order/details/update/", UpdateOrderDetailView.as_view(), name="order-details"),
    path("checkout/", CheckOutView.as_view(), name="checkout"),
    path("order/<int:order_id>/details/", OrderDetailView.as_view(), name="order-detail"),
    path("order/<int:order_id>/status/", OrderStatusUpdateView.as_view(), name="order-status"),
    path("order/<int:order_id>/pay/", InitializePaymentView.as_view(), name="initialize-payment"),
    path("order/verify/<str:reference>/", VerifyPaymentView.as_view(), name="verify-payment"),
    path("webhook/paystack/", PayStackWebhookView.as_view(), name="webhook-paystack"),
    path("order/<int:order_id>/review/", CreateReviewView.as_view(), name="create-review"),
    path("order/<int:order_id>/review/update/", UpdateReviewView.as_view(), name="update-review"),
    path("order/<int:order_id>/review/details/", OrderReviewDetailView.as_view(), name="order-review-detail"),
    path("foods/<int:food_id>/reviews/", FoodReviewsView.as_view(), name="food-reviews"),
    path("food/<int:food_id>/details/", FoodDetailView.as_view(), name="food-detail"),
    path("vendors/", VendorListView.as_view(), name="vendors"),
    path("vendor/<slug:slug>/details/", VendorDetailView.as_view(), name="vendor-detail"),
    path("vendor/<slug:slug>/foods/", VendorFoodListView.as_view(), name="vendor-foods"),
    path("vendor/<slug:slug>/reviews/", VendorReviewsView.as_view(), name="vendor-reviews"),
    path("vendor/apply/", VendorRegistrationView.as_view(), name="vendor-register"),
    path("vendor/dashboard/", VendorDashboardView.as_view(), name="vendor-dashboard"),
    path("vendor/dashboard/stats/", VendorDashboardStatsView.as_view(), name="vendor-dashboard-stats"),
    path("vendor/profile/update/", VendorProfileUpdateView.as_view(), name="vendor-profile-update"),
    path("vendor/create_food/", VendorFoodCreateView.as_view(), name="vendor-food-create"),
    path("vendor/all_foods/", VendorFoodsView.as_view(), name="all_foods"),
    path("vendor/food/<int:food_id>/details/", VendorFoodDetailView.as_view(), name="vendor-food-details"),
    path("vendor/food/<int:food_id>/available/", VendorFoodToggleAvailabilityView.as_view(), name="vendor-available-food"),
    path("vendor/all_orders/", VendorOrderListView.as_view(), name="vendor-orders"),
    path("vendor/order/<int:order_id>/details/", VendorOrderDetailView.as_view(), name="vendor-order-details"),
    path("admin/vendors/", AdminVendorListView.as_view(), name="admin-vendors"),
    path("admin/vendor/<int:vendor_id>/details/", AdminVendorDetailView.as_view(), name="admin-vendor-detail"),
    path("admin/vendor/<int:vendor_id>/approve/", AdminApproveVendorView.as_view(), name="admin-vendor-approve"),
    path("admin/vendor/<int:vendor_id>/reject/", AdminVendorRejectView.as_view(), name="admin-vendor-reject"),
    path("admin/vendor/<int:vendor_id>/activate/", AdminVendorActivateView.as_view(), name="admin-vendor-activate"),
    path("admin/vendor/<int:vendor_id>/deactivate/", AdminVendorDeactivateView.as_view(), name="admin-vendor-deactivate"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("category/<slug:slug>/foods/", CategoryFoodsView.as_view(), name="category-foods"),
    path("admin/category/create/", AdminCategoryCreateView.as_view(), name="admin-category-create"),
    path("admin/category/<int:category_id>/details/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),

]
