# Generated by Django 5.2.9 on 2026-05-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_plan_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='free_delivery',
            new_name='analytics_access',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='priority_support',
            new_name='can_receive_reviews',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='can_leave_reviews',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='plan',
            name='max_food_listings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='priority_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='food.vendor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_orders_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium')], max_length=50, unique=True),
        ),
    ]
