# Generated by Django 5.2.9 on 2026-05-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_rename_free_delivery_plan_analytics_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('SUBSCRIBED', 'Subscribed'), ('EXPIRED', 'Expired'), ('EXPIRING_SOON', 'Expiring soon'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.plan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='food.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
