# Generated by Django 5.2.9 on 2026-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
